query GetCountryOfOrigin($udcs: [String]!) {
  getCountryOfOrigin(udcs: $udcs) {
    data {
      udc
      description
      text
    }
    errors {
      message
      code
    }
    performanceData {
      key
      value
    }
  }
}
