query getItemPricing(
  $itemNumber: String!
  $customer: String
  $effectiveDate: String
  $branch: String
) {
  getItemPricing(
    itemNumber: $itemNumber
    customer: $customer
    effectiveDate: $effectiveDate
    branch: $branch
  ) {
    itemPrices {
      adjustment
      cB
      currency
      customerGroup
      customer
      effectiveDate
      itemNumber
      price
      quantity
      uom
    }
  }
}
